# Generated by Django 6.0.3 on 2026-04-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='skills',
        ),
    ]
