# Generated by Django 6.0.2 on 2026-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
