# Generated by Django 6.0.3 on 2026-04-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournlEntry',
            new_name='JournalEntry',
        ),
    ]
